### PR TITLE
Added Landing page

### PR DESCRIPTION
**Pull request by Abhijeet43**
I have created landing page for component library, Please check and give feedback

### CODE REVIEW

**Comment by gadgetfather** [comment]
Colors and fonts are awesome ! 
just center the middle text "design beautiful UI and ..."
image

**Comment by SatwikaKacham** [comment]
Heyy it's pretty good and responsive. The color contrast is nice.

**Review by RakshaPawar108 — COMMENTED** [review]
The code is pretty clean and it's great to see modular code. The design is also beautiful and responsive. Great work!! 😄

**Review by RakshaPawar108 — APPROVED** [review]

**Comment by Husain01** [comment]
Looks clean and great. Nice work.

**Review by Husain01 — APPROVED** [review]

**Review by gadgetfather — APPROVED** [review]
Looks great now ! 👍

**Pull request merged**
