### PR TITLE
Added: Typography conclusion

### PR DESCRIPTION
**Pull request by Abhijeet43**
Added Typography and conclusion sections

### CODE REVIEW

**Comment by vermasavita** [comment]
"Getting started" is taking two lines. You can fix that in one line.

**Comment by vermasavita** [comment]
Check code box bottom padding #3

**Comment by vermasavita** [comment]
Conclusion page -> Footer --> Component 

There is no link. #3

**Comment by Abhijeet43** [comment]
> Conclusion page -> Footer --> Component
> 
> There is no link. #3

The component link is blank because the components are not created yet...Will update them as soon as the components are ready

**Comment by AnkurChunekar** [comment]
Great work abhijeet, keep going, approving.

**Review by AnkurChunekar — APPROVED** [review]

**Comment by Abhijeet43** [comment]
> "Getting started" is taking two lines. You can fix that in one line.

Thanks for noticing will fix it

**Review by mohammed-sas — APPROVED** [review]
your code is good to merge

**Review by vermasavita — COMMENTED** [review]
Good to merge @Abhijeet43

**Pull request merged**
